import { useState } from "react";
import { KeyboardAvoidingView, View } from "react-native";
import { Link, router } from "expo-router";
import { Button, Card, Text, TextInput } from "react-native-paper";
import { authClient } from "@/lib/auth-client";
import { Screen } from "@/components/screen";
import { useNotice } from "@/components/snackbar";
const demos = [{ label: "Quản trị", email: "admin@demo.vn" }, { label: "Giám đốc", email: "director@demo.vn" }, { label: "Đội thi công", email: "site@demo.vn" }, { label: "Cửa hàng", email: "supplier@demo.vn" }];
export default function Login() { const notice = useNotice(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false); async function submit() { setLoading(true); const result = await authClient.signIn.email({ email, password }); setLoading(false); if (result.error) return notice("Email hoặc mật khẩu không đúng."); notice("Đăng nhập thành công"); router.replace("/"); } return <KeyboardAvoidingView style={({ flex: 1 } as any)} behavior={process.env.EXPO_OS === "ios" ? "padding" : undefined}><Screen><Card><Card.Title title="Quản lý đặt vật tư" subtitle="Đăng nhập để tiếp tục" /><Card.Content style={{ gap: 12 }}><TextInput label="Email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} /><TextInput label="Mật khẩu" secureTextEntry value={password} onChangeText={setPassword} /><Button mode="contained" loading={loading} disabled={loading || !email || !password} onPress={submit}>Đăng nhập</Button><Text variant="labelMedium">Tài khoản demo (mật khẩu: 123456)</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{demos.map((item) => <Button key={item.email} compact mode="outlined" onPress={() => { setEmail(item.email); setPassword("123456"); }}>{item.label}</Button>)}</View><Link href="/docs" asChild><Button>Xem tài liệu hướng dẫn</Button></Link></Card.Content></Card></Screen></KeyboardAvoidingView>; }
