import { useMemo, useState } from "react";
import { router, Stack } from "expo-router";
import { Button, Card, Searchbar, Text } from "@/components/ui";
import { Screen, StateView, Empty } from "@/components/screen";
import { SelectMenu } from "@/components/select-menu";
import { StatusChip } from "@/components/status-chip";
import { useApi } from "@/hooks/use-api";
import { formatDate, formatVND, statusLabels } from "@/lib/format";
type Row = { id: number; code: string; projectName: string; creatorName: string; supplierName?: string; createdAt: string; status: keyof typeof statusLabels; total: string };
export default function Orders() { const query = useApi<Row[]>("/api/orders"); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [descending, setDescending] = useState(true); const rows = useMemo(() => (query.data ?? []).filter((row) => (status === "all" || row.status === status) && `${row.code} ${row.projectName} ${row.creatorName}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => (Date.parse(a.createdAt) - Date.parse(b.createdAt)) * (descending ? -1 : 1)), [query.data, search, status, descending]); return <Screen><Stack.Screen options={{ title: "Đơn đặt vật tư" }} /><Searchbar placeholder="Tìm mã đơn, công trình, người tạo" value={search} onChangeText={setSearch} /><SelectMenu value={status} onChange={setStatus} options={[{ value: "all", label: "Tất cả trạng thái" }, ...Object.entries(statusLabels).map(([value, label]) => ({ value, label }))]} /><Button mode="outlined" onPress={() => setDescending((value) => !value)}>Ngày: {descending ? "mới nhất" : "cũ nhất"}</Button><StateView loading={query.loading} error={query.error} retry={query.refresh}>{rows.length === 0 ? <Empty>Chưa có đơn nào.</Empty> : rows.map((row) => <Card key={row.id} onPress={() => router.push(`/orders/${row.id}`)}><Card.Title title={row.code} subtitle={`${row.projectName} · ${formatDate(row.createdAt)}`} right={() => <StatusChip status={row.status} />} /><Card.Content><Text selectable>{row.creatorName}</Text><Text selectable variant="titleMedium">{formatVND(row.total)}</Text></Card.Content></Card>)}</StateView></Screen>; }
