import { router, Stack } from "expo-router";
import { Button, Card, Text } from "@/components/ui";
import { Screen, StateView } from "@/components/screen";
import { BarChart } from "@/components/charts";
import { StatusChip } from "@/components/status-chip";
import { useApi } from "@/hooks/use-api";
import { authClient, type AppUser } from "@/lib/auth-client";
import { formatDateTime, formatVND, roleLabels, statusLabels } from "@/lib/format";
type Data = { projectCount: number; pendingCount: number; approvedCount: number; materialCount: number; deliveredMonth: number; debt: number; statusRows: { status: keyof typeof statusLabels; value: number }[]; recentOrders: { id: number; code: string; status: keyof typeof statusLabels; total: string; createdAt: string; projectName: string; creatorName: string }[] };
export default function Dashboard() { const query = useApi<Data>("/api/dashboard"); const user = authClient.useSession().data?.user as AppUser | undefined; const quick = user?.role === "site" ? ["Đặt vật tư", "/orders/new"] : user?.role === "supplier" ? ["Đơn cần giao", "/delivery"] : user?.role === "admin" ? ["Duyệt đơn", "/approvals"] : ["Thống kê", "/reports"]; return <Screen><Stack.Screen options={{ title: "Tổng quan" }} /><Text selectable variant="headlineSmall">Xin chào, {user?.name}</Text><Text selectable>{user ? `Bảng điều khiển ${roleLabels[user.role]}` : ""}</Text><Button mode="contained" onPress={() => router.push(quick[1] as never)}>{quick[0]}</Button><StateView loading={query.loading} error={query.error} retry={query.refresh}>{query.data && <><Card><Card.Content style={{ flexDirection: "row", flexWrap: "wrap", gap: 18 }}><Metric label="Công trình" value={query.data.projectCount} /><Metric label="Chờ duyệt" value={query.data.pendingCount} /><Metric label="Cần giao" value={query.data.approvedCount} /><Metric label="Vật tư" value={query.data.materialCount} /></Card.Content></Card><Card><Card.Title title="Tài chính" /><Card.Content style={{ gap: 8 }}><Text selectable>Đã giao trong tháng: {formatVND(query.data.deliveredMonth)}</Text><Text selectable style={({ color: query.data.debt > 0 ? "#b91c1c" : "#15803d" } as any)}>Công nợ toàn hệ thống: {formatVND(query.data.debt)}</Text></Card.Content></Card><Card><Card.Title title="Đơn theo trạng thái" /><Card.Content><BarChart data={query.data.statusRows.map((row) => ({ name: statusLabels[row.status], value: row.value }))} /></Card.Content></Card><Text variant="titleMedium">Đơn đặt gần đây</Text>{query.data.recentOrders.map((order) => <Card key={order.id} onPress={() => router.push(`/orders/${order.id}`)}><Card.Title title={order.code} subtitle={`${order.projectName} · ${formatDateTime(order.createdAt)}`} right={() => <StatusChip status={order.status} />} /><Card.Content><Text selectable>{formatVND(order.total)}</Text></Card.Content></Card>)}</>}</StateView></Screen>; }
function Metric({ label, value }: { label: string; value: number }) { return <Card mode="contained" style={({ minWidth: "44%", flexGrow: 1 } as any)}><Card.Content><Text selectable variant="headlineMedium">{value}</Text><Text selectable>{label}</Text></Card.Content></Card>; }
