import { useState } from "react";
import { Stack } from "expo-router";
import { Card, Text } from "@/components/ui";
import { Screen, StateView, Empty } from "@/components/screen";
import { SelectMenu } from "@/components/select-menu";
import { BarChart } from "@/components/charts";
import { useApi } from "@/hooks/use-api";
import { formatNumber, formatPercent, formatVND } from "@/lib/format";
type Data = { projects: { id: number; code: string; name: string }[]; selectedId: number | null; totalBudget: number; totalActual: number; totalDiff: number; rows: { materialId: number; name: string; unit: string; group: string; budgetQty: number; budgetAmount: number; actualQty: number; actualAmount: number }[] };
export default function Reconcile() { const [project, setProject] = useState(""); const query = useApi<Data>(`/api/reconcile${project ? `?projectId=${project}` : ""}`); const data = query.data; return <Screen><Stack.Screen options={{ title: "Đối chiếu dự toán / thực tế" }} /><StateView loading={query.loading} error={query.error} retry={query.refresh}>{data && <><SelectMenu value={String(data.selectedId ?? "")} onChange={setProject} label="Chọn công trình" options={data.projects.map((item) => ({ value: String(item.id), label: `${item.code} · ${item.name}` }))} /><Card><Card.Content style={{ gap: 5 }}><Text selectable>Dự toán: {formatVND(data.totalBudget)}</Text><Text selectable>Thực tế: {formatVND(data.totalActual)}</Text><Text selectable style={({ color: data.totalDiff > 0 ? "#b91c1c" : "#15803d" } as any)}>Chênh lệch: {formatVND(data.totalDiff)}</Text></Card.Content></Card><Card><Card.Title title="Biểu đồ dự toán vs thực tế" /><Card.Content><BarChart money data={data.rows.map((row) => ({ name: row.name, value: row.actualAmount }))} /></Card.Content></Card>{data.rows.length === 0 ? <Empty>Chưa có dự toán hoặc phát sinh thực tế.</Empty> : data.rows.map((row) => { const over = row.actualAmount > row.budgetAmount && row.actualAmount > 0; const noBudget = row.budgetAmount === 0 && row.actualAmount > 0; return <Card key={row.materialId} style={(over || noBudget ? { backgroundColor: "#fef2f2" } : undefined) as any}><Card.Title title={row.name} subtitle={row.group} /><Card.Content><Text selectable>SL dự toán: {formatNumber(row.budgetQty)} {row.unit}</Text><Text selectable>SL thực tế: {formatNumber(row.actualQty)} {row.unit}</Text><Text selectable>Tiền dự toán: {formatVND(row.budgetAmount)}</Text><Text selectable>Tiền thực tế: {formatVND(row.actualAmount)}</Text><Text selectable style={({ color: over || noBudget ? "#b91c1c" : undefined } as any)}>{noBudget ? "Ngoài dự toán" : `${formatPercent(row.budgetAmount ? row.actualAmount / row.budgetAmount * 100 : 0)} so dự toán`}</Text></Card.Content></Card>; })}</>}</StateView></Screen>; }
