import { useState } from "react";
import { Button, Dialog, Portal, TextInput } from "@/components/ui";
import { api, jsonBody } from "@/lib/api";
import { useNotice } from "./snackbar";
import { useApi } from "@/hooks/use-api";
import { authClient, type AppUser } from "@/lib/auth-client";
import * as Linking from "expo-linking";
type ZaloOrder = { code: string; status: string; projectName: string; supplierContact?: { phone: string } | null; items: { name: string; qty: string; unit: string }[] };
export function OrderActions({ orderId, canApprove, canDeliver, onDone }: { orderId: number; canApprove: boolean; canDeliver: boolean; onDone: () => void }) { const notice = useNotice(); const order = useApi<ZaloOrder>(`/api/orders/${orderId}`).data; const user = authClient.useSession().data?.user as AppUser | undefined; const [loading, setLoading] = useState(false); const [rejecting, setRejecting] = useState(false); const [reason, setReason] = useState(""); async function run(path: string, body?: unknown) { setLoading(true); try { await api(`/api/orders/${orderId}/${path}`, { method: "POST", ...(body ? jsonBody(body) : {}) }); notice(path === "approve" ? "Đã duyệt đơn và phân bổ số liệu." : path === "deliver" ? "Đã đánh dấu giao hàng." : "Đã từ chối đơn."); setRejecting(false); onDone(); } catch (error) { notice(error instanceof Error ? error.message : "Thao tác thất bại."); } finally { setLoading(false); } } function openZalo() { if (!order?.supplierContact?.phone) return; const body = [`Đơn cần đặt: ${order.code}`, `Công trình: ${order.projectName}`, ...order.items.map((item) => `• ${item.name}: ${item.qty} ${item.unit}`)].join("\n"); const phone = order.supplierContact.phone.replace(/\D/g, "").replace(/^0/, "84"); void Linking.openURL(`https://zalo.me/${phone}?text=${encodeURIComponent(body)}`).catch(() => notice("Không thể mở Zalo.")); } const canSendZalo = order?.status === "approved" && !!order.supplierContact?.phone && (user?.role === "admin" || user?.role === "site"); return <>{canApprove && <><Button mode="contained" loading={loading} disabled={loading} onPress={() => run("approve")}>Duyệt đơn</Button><Button mode="contained" buttonColor="#b91c1c" disabled={loading} onPress={() => setRejecting(true)}>Từ chối</Button></>}{canDeliver && <Button mode="contained" loading={loading} disabled={loading} onPress={() => run("deliver")}>Đánh dấu đã giao</Button>}{canSendZalo && <Button mode="outlined" onPress={openZalo}>Gửi nội dung cần đặt qua Zalo</Button>}<Portal><Dialog visible={rejecting} onDismiss={() => setRejecting(false)}><Dialog.Title>Từ chối đơn</Dialog.Title><Dialog.Content><TextInput label="Lý do (không bắt buộc)" multiline value={reason} onChangeText={setReason} /></Dialog.Content><Dialog.Actions><Button onPress={() => setRejecting(false)}>Hủy</Button><Button textColor="#b91c1c" onPress={() => run("reject", { reason })}>Xác nhận</Button></Dialog.Actions></Dialog></Portal></>; }
