import { useEffect, useState } from "react";
import { router } from "expo-router";
import { Button, Card, Text, TextInput } from "@/components/ui";
import { SelectMenu } from "@/components/select-menu";
import { useApi } from "@/hooks/use-api";
import { api, jsonBody } from "@/lib/api";
import { useNotice } from "@/components/snackbar";

type Contact = { id: number; name: string; phone: string };
export function ProjectForm({ id }: { id?: string }) { const contacts = useApi<Contact[]>("/api/supplier-contacts"); const summary = useApi<{ project: { code: string; name: string; address?: string; status: string }; suppliers: Contact[]; defaultSupplier?: Contact | null }>(id ? `/api/projects/${id}/summary` : undefined); const notice = useNotice(); const [draft, setDraft] = useState({ code: "", name: "", address: "", status: "active" }); const [linked, setLinked] = useState<number[]>([]); const [defaultId, setDefaultId] = useState(""); const [saving, setSaving] = useState(false); useEffect(() => { if (!id || !summary.data) return; setDraft({ ...summary.data.project, address: summary.data.project.address ?? "" }); setLinked(summary.data.suppliers.map((item) => item.id)); setDefaultId(String(summary.data.defaultSupplier?.id ?? "")); }, [id, summary.data]); async function save() { setSaving(true); try { await api(id ? `/api/projects/${id}` : "/api/projects", { method: id ? "PATCH" : "POST", ...jsonBody({ ...draft, defaultSupplierContactId: defaultId ? Number(defaultId) : null, supplierContactIds: linked }) }); notice("Đã lưu công trình."); router.replace("/admin/projects"); } catch (error) { notice(error instanceof Error ? error.message : "Không thể lưu."); } finally { setSaving(false); } } return <Card><Card.Content style={{ gap: 12 }}><TextInput label="Mã công trình" value={draft.code} onChangeText={(code) => setDraft((v) => ({ ...v, code }))} /><TextInput label="Tên công trình" value={draft.name} onChangeText={(name) => setDraft((v) => ({ ...v, name }))} /><TextInput label="Địa chỉ" value={draft.address ?? ""} onChangeText={(address) => setDraft((v) => ({ ...v, address }))} /><SelectMenu label="Trạng thái" value={draft.status} onChange={(status) => setDraft((v) => ({ ...v, status }))} options={[{ value: "active", label: "Đang thi công" }, { value: "paused", label: "Tạm dừng" }, { value: "completed", label: "Hoàn thành" }]} /><Text variant="titleMedium">Đơn vị cung cấp liên quan</Text>{contacts.data?.map((item) => { const selected = linked.includes(item.id); return <Button key={item.id} mode={selected ? "contained" : "outlined"} onPress={() => setLinked((items) => selected ? items.filter((value) => value !== item.id) : [...items, item.id])}>{item.name}</Button>; })}<SelectMenu label="Đơn vị mặc định" value={defaultId} onChange={setDefaultId} options={[{ value: "", label: "Chưa chọn" }, ...(contacts.data?.filter((item) => linked.includes(item.id)).map((item) => ({ value: String(item.id), label: item.name })) ?? [])]} /><Button mode="contained" loading={saving} disabled={saving} onPress={save}>Lưu công trình</Button></Card.Content></Card>; }
